version: "3.4"

networks:
  local-network:
    ipam:
      config:
        - subnet: 1.0.0.0/16

services:   

  otel_collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - 43170:4317
      - 55680:55680
    networks:
      - local-network
    environment:
      LOKI_ENDPOINT: "http://loki:3100/loki/api/v1/push"
    depends_on:
      - loki

  prometheus:
    networks:
      - local-network
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    networks:
      - local-network
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000

  loki:
    image: grafana/loki
    ports:
      - "3100"
    networks:
      - local-network

  tempo:
    networks:
      - local-network
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      # - "4317:4317"  # otlp grpc
      # - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  loggingsandboxlistener:
    image: ${DOCKER_REGISTRY-}loggingsandboxlistener
    build:
      context: .
      dockerfile: LoggingSandbox.Listener/Dockerfile
    depends_on:
      - otel_collector
    networks:
      - local-network

  loggingsandboxsender:
    image: ${DOCKER_REGISTRY-}loggingsandboxsender
    build:
      context: .
      dockerfile: LoggingSandbox.Sender/Dockerfile
    depends_on:
      - otel_collector
    networks:
      - local-network
