version: '3.4'

networks:
  local-network:
    ipam:
      config:
        - subnet: 1.0.0.0/16
  
services:

  loggingsandboxlistener:
    image: ${DOCKER_REGISTRY-}loggingsandboxlistener
    build:
      context: .
      dockerfile: LoggingSandbox.Listener/Dockerfile
    depends_on:
      - jaeger
      - zipkin
    networks:
      - local-network

  loggingsandboxsender:
    image: ${DOCKER_REGISTRY-}loggingsandboxsender
    build:
      context: .
      dockerfile: LoggingSandbox.Sender/Dockerfile
    depends_on:
      - jaeger
      - zipkin
    networks:
      - local-network
      
  jaeger:
    hostname: jaeger
    image: jaegertracing/all-in-one:1.50
    ports:
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "16685:16685"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    environment:
      COLLECTOR_OTLP_ENABLED: true   
    networks:
      - local-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - local-network
