# configure the otel collector to take input and output to jaeger
receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:

  prometheus/metrics:
    endpoint: "0.0.0.0:8889"

  otlp/traces:
    tls:
      insecure: true
    endpoint: tempo:4317

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
    default_labels_enabled:
      exporter: true
      job: true   

processors:
  batch:

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: test

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
     traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
     metrics:
       receivers: [otlp]
       processors: [batch]
       exporters: [prometheus/metrics]
     logs:
       receivers: [otlp]
       processors: [resource]
       exporters: [loki]

