# configure the otel collector to take input and output to jaeger
receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

exporters:

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    tls:
      insecure: true
    endpoint: jaeger:4317

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
    default_labels_enabled:
      exporter: true
      job: true   
  
  logging:
    # loglevel: debug

connectors:
  spanmetrics:

processors:
  batch:

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: test

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [spanmetrics, otlp]

    # The spanmmetrics exporter and reciever are linked, allowing traces to be converted to metrics.
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [resource]
      exporters: [loki, logging]  

    # metrics:
    #   receivers: [otlp]
    #   processors: []
    #   exporters: [otlp, otlphttp]
    # logs:
    #   receivers: [otlp]
    #   processors: []
    #   exporters: [otlp, otlphttp]
    #     receivers:
    #   otlp:
    #     protocols:
    #       grpc:
    #       http:
    # processors:
    #   resource:
    #     attributes:
    #       - action: insert
    #         key: loki.resource.labels
    #         value: service.name, k8s.container.name, k8s.namespace.name, k8s.pod.name
    # exporters:
    #   debug:
    #     verbosity: detailed
    #   loki:
    #     endpoint: "http://loki.default:3100/loki/api/v1/push"
    #     tls:
    #       insecure: true
    #     default_labels_enabled:
    #       exporter: true
    #       job: true   
    # service:
    #   pipelines:
    #     logs:
    #       receivers: [otlp]
    #       processors: [resource]
    #       exporters: [loki]  